# Generated by Django 4.2.1 on 2023-10-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allfurnitures', '0007_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='allfurnitures/users/default.jpg', upload_to='users'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='allfurnitures.furniture'),
        ),
    ]
